services:
  camera_pooling:
    container_name: camera_pooling
    build: .
    ports:
      - "8089:8000"
    volumes:
      - /var/screenshots:/var/screenshots
    env_file: ../.env
    networks:
      - swag_network
    restart: always

networks:
  swag_network:
    driver: bridge
    external: true
