services:
  camera_pooling:
    container_name: camera_pooling
    build: .
#    ports:
#      - "8089:8000"
    volumes:
      - /var/screenshots:/var/screenshots
    env_file: ../.env
    networks:
      - swag_network
    restart: always

    healthcheck:
#      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/"]
      test: ["CMD-SHELL", "curl -sS http://localhost:8000 | grep 'healthy' || exit 1"]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 5s

networks:
  swag_network:
    driver: bridge
    external: true
