services:
  deep_face:
    container_name: deep_face
    hostname: deep_face
    build: .
#    ports:
#      - "8088:8000"
#      - "8055:5000"
    volumes:
      - /root/.deepface:/root/.deepface
    environment:
      - CUDA_VISIBLE_DEVICES=0
    networks:
      - swag_network
    restart: always

networks:
  swag_network:
    driver: bridge
    external: true
