services:
  kv_db:
    build: .
    container_name: kv_db
    hostname: kv_db
#    ports:
#      - "8082:5000"
    environment:
      DB_FOLDER: /var/screenshots
    volumes:
      - /var/screenshots:/var/screenshots
    networks:
      - swag_network
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:5000 | grep 'healthy' || exit 1"]
      interval: 180s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  swag_network:
    driver: bridge
    external: true
