services:
  face_recognition:
    container_name: face_recognition
    hostname: face_recognition
    build: .
#    ports:
#      - "8088:8000"
    volumes:
      - /var/screenshots:/var/screenshots
    networks:
      - swag_network
    restart: always

networks:
  swag_network:
    driver: bridge
    external: true
